name: openexchangerates
description: Open Exchange Rates API client for Dart
version: 0.1.0
repository: https://github.com/maxint-app/openexchangerates.dart

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.7.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0
  
dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.24.0
  
